import { Poppins } from "next/font/google";
import localFont from "next/font/local";

import "./globals.css";
import HeaderComponent from "@/components/layout/Header";

const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

export const fontBn = localFont({
  src: "../../public/fonts/mayaboti-normal.ttf",
});

export const metadata = {
  title: {
    default: "Fun Cub",
    template: "%s | Fun Cub",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <HeaderComponent />
        {children}
      </body>
    </html>
  );
}
